#define _INTEGER "INTEGER"
#define _FLOAT "FLOAT"
#define _STRING "STRING"
#define _BOOL "BOOL"

#define _SEMICOLON ";"
#define _SPACE " "
#define _N "/n"
#define _R "/r"
#define _T "/t"
#define _LEFT_COLLIBRACE "{"
#define _RIGHT_COLLIBRACE "}"

#define _ID "ID"
#define _ASSIGMENT_EXPRESSION "ASSIGMENT_EXPRESSION"
#define _EQ "="
#define _PEQ "+="
#define _MEQ "-="
#define _BEq "*="
#define _DEQ "/="
#define _POWEQ "^="
#define _MODEQ "%="
#define _AEQ "&="
#define _OEQ "|="

#define _BINARY_OP "BINARY_OP"
#define _SUM "+"
#define _SUB "-"
#define _MUL "*"
#define _DIV "/"
#define _MOD "%"
#define _POW "^"
#define _LEFT_PARENTHESIS "("
#define _RIGHT_PARENTHESIS ")"

#define _IGNORE "IGNORE"
#define _ERROR "ERROR"
#define _EOF "EOF"
#define _PROGRAM "PROGRAM"
#define _EXPRESSION_STATEMENT "EXPRESSION_STATEMENT"
#define _BLOCK_STATEMENT "BLOCK_STATEMENT"

extern const char* symbols[25];