#define _INTEGER "INTEGER"
#define _FLOAT "FLOAT"
#define _STRING "STRING"
#define _BOOL "BOOL"
#define _NULL "NULL"

#define _RANGE "RANGE"
#define _INCL_RANGE ".."
#define _EXCL_RANGE "..."

#define _SEMICOLON ";"
#define _COMA ","
#define _SPACE " "
#define _N "/n"
#define _R "/r"
#define _T "/t"
#define _LEFT_COLLIBRACE "{"
#define _RIGHT_COLLIBRACE "}"

#define _ID "ID"
#define _ASSIGMENT_EXPRESSION "ASSIGMENT_EXPRESSION"
#define _VARIABLE_STATEMENT "VARIABLE_STATEMENT"
#define _VARIABLE_DECLARATION "VARIABLE_DECLARATION"
#define _EQ "="
#define _PEQ "+="
#define _INCR "++"
#define _DECR "--"
#define _MULTR "**"
#define _DVDR "//"
// #define _MODR "%%"
#define _MEQ "-="
#define _BEQ "*="
#define _DEQ "/="
#define _POWEQ "^="
#define _MODEQ "%="
#define _AEQ "&="
#define _OEQ "|="
#define _COM_EQ "=="
#define _COM_GT ">"
#define _COM_GT_EQ ">="
#define _COM_LT "<"
#define _COM_LT_EQ "<="
#define _COM_N "!"
#define _COM_N_EQ "!="
#define _LOGICAL_EXPRESSION "LOGICAL_EXPRESSION"
#define _COM_AND "&&"
#define _COM_OR "||"

#define _BINARY_OP "BINARY_OP"
#define _UNARY_OP "UNARY_OP"
#define _SUM "+"
#define _SUB "-"
#define _MUL "*"
#define _DIV "/"
#define _MOD "%"
#define _POW "^"
#define _LEFT_PARENTHESIS "("
#define _RIGHT_PARENTHESIS ")"

#define _IGNORE "IGNORE"
#define _ERROR "ERROR"
#define _EOF "EOF"
#define _PROGRAM "PROGRAM"
#define _EXPRESSION_STATEMENT "EXPRESSION_STATEMENT"
#define _BLOCK_STATEMENT "BLOCK_STATEMENT"

#define _MEMBER_EXPRESSION "MEMBER_EXPRESSION"
#define _DOT "."
#define _LEFT_BRACKET "["
#define _RIGHT_BRACKET "]"

extern const char* symbols[35];

#define _VAR "var"

#define _FOR_STATEMENT "FOR_STATEMENT"
#define _FOR "for"
#define _IN "in"

#define _LOOP_STATEMENT "LOOP_STATEMENT"
#define _LOOP "loop"
#define _BRAKE "break"

#define _IF_STATEMENT "IF_STATEMENT"
#define _IF "if"
#define _ELSE_IF_STATEMENT "ELSE_IF_STATEMENT"
#define _ELSE_IF "elif"
#define _ELSE_STATEMENT "ELSE_STATEMENT"
#define _ELSE "else"

#define _SWITCH_STATEMENT "SWITCH_STATEMENT"
#define _SWITCH "switch"
#define _CASE "case"

#define _FUNC_DECL "FUNCTION_DECLARATION"
#define _FUNC "func"

#define _RET_STATEMENT "RET_STATEMENT"
#define _RET "ret"

#define _CALL_EXPRESSION "CALL_EXPRESSION"

extern const char* keywords[11];